---
title: "interation_zoom_rj"
author: "pedro santos"
date: "2026-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

```{r cars}
library(arrow)
library(dplyr)
library(htmlwidgets)
library(geobr)
library(sf)
library(geoarrow)
library(h3jsr)
library(freestiler)
library(sf)
library(httr)
library(jsonlite)
library(mapgl)
library(mapview)
library(skimr)
library(h3jsr)
library(scales)
library(DBI)
library(duckdb)
library(purrr)
mapview::mapviewOptions(platform = 'leafgl')

```



```{r}
preparar_hex <- function(caminho_parquet) {
  read_parquet(caminho_parquet) |>
    group_by(h3_address, year, h3_res) |>
    summarise(across(c(F001, T001), ~sum(.x, na.rm = TRUE)), .groups = "drop") |>
    as.data.frame() |>
    mutate(geometry = cell_to_polygon(h3_address)) |>
    st_as_sf(crs = 4326)
}
```

```{r}
hex_res4_23 <- preparar_hex("../data/rais_h3_2023_4.parquet")
hex_res6_23 <- preparar_hex("../data/rais_h3_2023_6.parquet")
hex_res8_23 <- preparar_hex("../data/rais_h3_2023_8.parquet")
```


```{r liga_servidor, eval=FALSE}
file.remove("hex.pmtiles") # garante que começa do zero

freestile(
  list(
    h3_r04 = hex_res4_23,
    h3_r06 = hex_res6_23,
    h3_r08 = hex_res8_23
  ),
  "hex.pmtiles"
)

serve_tiles(".", port = 8080)
```


```{r}
resolucoes <- list(
  list(res = 4, min_zoom = 0, max_zoom = 7),
  list(res = 6, min_zoom = 7, max_zoom = 10),
  list(res = 8, min_zoom = 10, max_zoom = 14)
)


fill <- interpolate(
  column = "F001",
  values = c(0, 25, 50, 100, 200),   # ajuste com quantile(hex_res6$F001, ...)
  stops = viridisLite::viridis(5)
)

```


```{r}
# add_hex_layer <- function(map, info) {
#   add_fill_layer(
#     map,
#     id = sprintf("fill-h3-r%02d", info$res),
#     source = "hex",
#     source_layer = sprintf("h3_r%02d", info$res),
#     fill_color = fill,
#     fill_opacity = 0.85,
#     fill_outline_color = "rgba(255,255,255,0.3)",
#     min_zoom = info$min_zoom,
#     max_zoom = info$max_zoom,
#     tooltip = "F001: {F001}<br>T001: {T001}"
#   )
# }
# 
# maplibre(bounds = hex_res6) |>
#   add_pmtiles_source(id = "hex", url = "http://localhost:8080/hex.pmtiles") |>
#   reduce(resolucoes, add_hex_layer, .init = _)

```

```{r}
add_hex_layer <- function(map, info) {
  add_fill_layer(
    map,
    id = sprintf("fill-h3-r%02d", info$res),
    source = "hex",
    source_layer = sprintf("h3_r%02d", info$res),
    fill_color = fill,
    fill_opacity = 0.85,
    fill_outline_color = "rgba(255,255,255,0.3)",
    min_zoom = info$min_zoom,
    max_zoom = info$max_zoom,
    tooltip = "F001: {F001}<br>T001: {T001}"
  )
}


mapa_base_novo <- maplibre(bounds = hex_res6_23) |>
  add_pmtiles_source(
    id = "hex", 
    url = "http://localhost:8080/hex_res6_23.pmtiles" # <-- URL atualizada aqui!
  )

# 2. Aplique o reduce sem usar o pipe com o placeholder "_"
purrr::reduce(.x = resolucoes, .f = add_hex_layer, .init = mapa_base_novo)
```

