---
title: "rj_state"
author: "Pedro Santos"
subtitle: Percepção sobre como os dados se comportam após a aplicação da função de
  censura dos dados aos hexagonos 
output:
  html_document: default
  self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r cars}
library(mapgl)
library(htmlwidgets)
library(tidyverse)
library(ipeadatalake)
library(geobr)
library(sf)
library(mapview)
library(leafgl)
library(dplyr)
library(geoarrow)
library(viridisLite)
library(viridis)
library(skimr)
library(h3jsr)
library(scales)
library(DBI)
library(duckdb)
# source("../R/agregar_escolas.R")
# source("../R/censura_funcao.R")
# source("../R/encontrar_vizinho.R")
# source("../R/escolas_por_h3.R")
mapview::mapviewOptions(platform = 'leafgl')

```


```{r}
#dataset do rio de janeiro na resolução 8

df <- arrow::open_dataset("../data/rais_h3_2022_6.parquet") %>% 
  collect()
df_23 <- arrow::open_dataset("../data/rais_h3_2023_6.parquet") %>% 
  collect()
# df <- arrow::open_dataset("../data/rais_h3_2022_4.parquet") |> 
#   sf::st_as_sf()
#encontrar os vizinhos de cada h3
#df_vizinhos <- encontrar_vizinho(tabela_raw = df, id_hex = 'h3_address')

#df aplicado aos dados de censura - função retorna colunas de nome "contagem_firmas" e "contagem_empregos"
# df_cens <- censura(tabela_raw = df, tabela_vizinhos = df_vizinhos, barreira = 3, col_name = 'F001', col_name2 = "T001")


#salva em arquivo o df_censurado
#arrow::write_parquet(df_cens, './rio_grade_08_censurado_rais2019.parquet')


# summary(df$qt_firmas)
# summary(df_cens$contagem)

# density(df$qt_firmas) |> plot()
# # density(df_cens$contagem) |> plot()
# 
# #df_temporário para testar a aplicação em mapview
# temp <- df_cens |> sf::st_drop_geometry()
# 
# #união entre as tabelas temp (censurada sem feometria e as tabelas do rj)
# aaa <- left_join(df, temp, by = c('h3_address' = 'id_max_vizinho'))
# #salva em arquivo o df_censurado
# #arrow::write_parquet(df_cens, './rio_grade_08_censurado_rais2019.parquet')
# #criação das colunas com a diferença entre o dataset com firmas censuradas e as firmas anteriores  
# #renomeação das colunas em firmas/empregos antes e depois
# aaa <- aaa |> 
#     rename(qt_firmas_antes = qt_firmas,
#            qt_empregos_antes = qt_empregos)
# 
# 
# aaa <- aaa |> mutate(diff_firmas = firmas_depois - qt_firmas_antes,
#                      diff_empregos = empregos_depois - qt_empregos_antes)
```

```{r}
# Passo 1: Criar a geometria espacial a partir do h3_address e definir o CRS

df <- df |> 
  group_by(h3_address, year, h3_res) |> 
  summarise(across(c(F001, T001), ~sum(.x, na.rm = TRUE)))

df_espacial <- df |>
  as.data.frame() |> # Garante que é um dataframe puro (remove heranças do arrow/group_by)
  mutate(geometry = cell_to_polygon(h3_address)) |>
  st_as_sf(crs = 4326) # <- ESSENCIAL: Informa que as coordenadas são Lat/Lon (WGS84)

#summary(df$T001)
# 2. Quebras por quantis
quebras_f22 <- quantile(df$F001, probs = seq(0, 1, by = 0.2), na.rm = TRUE)
quebras_f22 <- unique(quebras_f22)
quebras_t22 <- quantile(df$T001, probs = seq(0, 1, by = 0.2), na.rm = TRUE)
quebras_t22 <- unique(quebras_t22)

df_23 <- df_23 |> 
  group_by(h3_address, year, h3_res) |> 
  summarise(across(c(F001, T001), ~sum(.x, na.rm = TRUE)))

df_23_espacial <- df_23 |>
  as.data.frame() |> # Garante que é um dataframe puro (remove heranças do arrow/group_by)
  mutate(geometry = cell_to_polygon(h3_address)) |>
  st_as_sf(crs = 4326) # <- ESSENCIAL: Informa que as coordenadas são Lat/Lon (WGS84)

#summary(df_23$T001)
# 2. Quebras por quantis
quebras_f23 <- quantile(df_23$F001, probs = seq(0, 1, by = 0.2), na.rm = TRUE)
quebras_f23 <- unique(quebras_f23)
quebras_t23 <- quantile(df_23$T001, probs = seq(0, 1, by = 0.2), na.rm = TRUE)
quebras_t23 <- unique(quebras_t23)


# 4. Plota o mapa de firmas 
firmas_23 <- mapview(df_23_espacial, zcol = "F001", layer.name = "Total (F001) Firmas", at = quebras_f23,
        col.regions = cividis(5))
firmas_23

```


```{r}
firmas_2022 <- mapview(df_espacial, zcol = "F001", layer.name = "Total (F001) Firmas", at = quebras_f22,
        col.regions = cividis(5))
firmas_2022

#firmas_2022 <- mapview(df_espacial, zcol = "F001", layer.name = "Total (F001) Firmas", at = quebras_f,
 #       col.regions = cividis(5))

```


```{r}

# freestile(df_23_espacial, "hex.pmtiles", layer_name = "h3_r06")
# serve_tiles(".", port = 8080)
# 
# maplibre(bounds = df_23_espacial) |>
#   add_pmtiles_source(id = "hex", url = "http://localhost:8080/hex.pmtiles") |>
#   add_fill_layer(
#     id = "fill-hex",
#     source = "hex",
#     source_layer = "h3_r06",
#     fill_color = interpolate(
#       column = "F001",
#       values = c(0, 25, 50, 100, 200),
#       stops = viridisLite::viridis(5)
#     ),
#     fill_opacity = 0.85,
#     fill_outline_color = "rgba(255,255,255,0.3)",
#     tooltip = "F001: {F001}<br>T001: {T001}"
#   )
```


# Comparação entre empregos antes e depois: 
```{r}

# 4. Plota o mapa de empregos 
trabalhadores_23 <- mapview(df_23_espacial, zcol = "T001", layer.name = "Total (T001) Empregos", at = quebras_t23,
        col.regions = cividis(5))
trabalhadores_23

```

```{r}
trabalhadores_22 <- mapview(df_espacial, zcol = "T001", layer.name = "Total (T001) Empregos", at = quebras_t22,
        col.regions = cividis(5))
trabalhadores_22
```
```{r}
df_23 |> 
  ungroup() |> 
    select(F001, T001) |> 
    summary() |> 
    knitr::kable(caption = "Estatisticas Principais - 2023")
```




```{r}

dados_long <- df_23 %>%
  # Remove a geometria espacial, virando uma tabela normal
  st_drop_geometry() %>% 
  # Seleciona as colunas
  select(qt_firmas_antes, firmas_depois) %>%
  # Como a geometria sumiu, o everything() vai funcionar perfeitamente
  pivot_longer(cols = everything(), 
               names_to = "periodo", 
               values_to = "quantidade") %>%
  mutate(periodo = recode(periodo, 
                          "qt_firmas_antes" = "Antes", 
                          "firmas_depois" = "Depois"))


```


```{r}
df |> 
  ungroup() |> 
  select(F001, T001) |> 
  summary() |> 
  knitr::kable(caption = "Estatisticas Principais - 2022")
```
##gráfico de área

```{r}
df_completo <- bind_rows(df, df_23) |>
  # Transformar a coluna year em fator (categórica) é essencial 
  # para o ggplot entender que são duas cores distintas
  mutate(year = as.factor(year))


# Plotar com facet_wrap
ggplot(df_completo, aes(x = F001)) +
  # Gerando o histograma/área com bins
  geom_area(stat = "bin", bins = 50, fill = "#440154", alpha = 0.7) +
  
  # O segredo: separar em duas colunas (lado a lado)
  facet_wrap(~year, ncol = 2) + 
  
  labs(
    title = "Comparacao da Distribuicao de Firmas por Hexagono",
    x = "Numero de Firmas (F001)",
    y = "Quantidade de Hexagonos"
  ) +
  theme_minimal()
```

##lei de zipf
 
```{r}

ggplot(df_completo, aes(x = T001)) +
  # Usei uma cor diferente (verde azulado) para distinguir do gráfico de firmas
  geom_area(stat = "bin", bins = 50, fill = "#21908C", alpha = 0.7) +
  facet_wrap(~year, ncol = 2) + 
  
  # A mágica acontece aqui:
  # 1. scale_x_log10(): Distribui a cauda longa dos dados
  # 2. labels = label_number(): Remove a notação científica e formata como 10.000, 100.000, etc.
  #scale_x_log10(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  scale_x_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +  
  labs(
    title = "Comparacao da Distribuicao de Trabalhadores por Hexagono",
    x = "Numero de Trabalhadores (T001) - Escala Log",
    y = "Quantidade de Hexagonos"
  ) +
  theme_minimal()
```

